global using MongoDB.Bson.Serialization.Attributes;
global using MotorcycleRent.Domain.Exceptions;
global using MotorcycleRent.Domain.Models;
global using MotorcycleRent.Domain.Models.Enums;
global using System.Security.Claims;
global using System.Text.Json.Serialization;
global using MongoDB.Driver;
global using MotorcycleRent.Domain.Entities;
global using System.Linq.Expressions;